# Generated by Django 4.2 on 2023-10-22 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0002_review_comingsoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='descreption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='genre',
            name='color',
            field=models.CharField(choices=[('badge-primary', 'Primary'), ('badge-secondary', 'Secondary'), ('badge-success', 'Success'), ('badge-danger', 'Danger'), ('badge-warning', 'Warning'), ('badge-info', 'Info'), ('badge-light', 'Light'), ('badge-dark', 'Dark')], default='badge-primary', max_length=40),
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='movie_cover'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='ComingSoon',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
